name: Build Termux Fn-Edition

on:
  workflow_dispatch: # Permite que você clique num botão no GitHub para buildar quando quiser

jobs:
  build-termux:
    name: Build para Android (Termux)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar o Target no Rust
      run: |
        echo "targets = ['aarch64-linux-android']" >> rust-toolchain.toml

    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
      with:
        cache: true # Ativa o cache para os próximos builds irem voando

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b # Versão estável do NDK com suporte ao LLVM/Clang

    - name: Compilar o Nushell Customizado
      run: |
        # Configura as variáveis de ambiente para o Cargo saber onde está o Linker do Android
        export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang
        
        # Builda o workspace inteiro em modo Release focado no Termux
        cargo build --release --target aarch64-linux-android --workspace

    - name: Fazer Upload do Binário
      uses: actions/upload-artifact@v4
      with:
        name: nu-fn-termux
        path: target/aarch64-linux-android/release/nu
